env:
  es6: true
  mocha: true
  node: true
extends: 'airbnb-base'
parserOptions:
  ecmaFeatures:
    modules: true
  sourceType: module
plugins:
  - mocha
globals:
    jest: readable
    expect: readable
    executeQuery: false
rules:
  "import/no-extraneous-dependencies":
    - error
    -
      devDependencies: true
  "mocha/no-exclusive-tests": error
  generator-star-spacing: off
  no-unused-expressions: off
  "no-console": off
  "newline-per-chained-call": off
  "one-var-declaration-per-line": off
  "no-param-reassign": off
  "camelcase": off
  "one-var": off
  "max-len": off
  "array-callback-return": off
  "class-methods-use-this": off
  "arrow-body-style": off
  "func-names": off
  "import/prefer-default-export": off
  "no-shadow": off
  "no-prototype-builtins": off
  "consistent-return": off
  "no-use-before-define": off
  "prefer-rest-params": off
  "no-restricted-properties": off