on: pull_request
name: Run Tests
jobs:
  npmCit:
    name: npm cit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm cit
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        entrypoint: npm
        args: cit
